spring:
  application:
    name: gestion-vacaciones

  data:
    mongodb:
      host: localhost
      port: 27017
      database: gestion_vacaciones_db

server:
  port: 8080

logging:
  level:
    com:
      iem:
        tfm: DEBUG